env:
    CIRRUS_SHELL: bash

task:
  name: "Build TWRP"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 4
      memory: 8G

  Build_script:
      - mkdir /root/work
      - cd /root/work
      - git clone https://gitlab.com/OrangeFox/sync.git
      - bash ./legacy/orangefox_sync_legacy.sh --branch fox_9.0 --path /root/ofox
      - cd /root/ofox
      - git clone https://gitlab.com/OrangeFox/device/whyred.git device/xiaomi/whyred
      - bash -c "source build/envsetup.sh export ALLOW_MISSING_DEPENDENCIES=true export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1 export LC_ALL="C" lunch omni_whyred-eng && mka recoveryimage -j4  "
      - repo sync -j4
      - export ALLOW_MISSING_DEPENDENCIES=true
      - bash -c "source ./build/envsetup.sh && lunch omni_whyred-eng && mka recoveryimage"

