env:
    CIRRUS_SHELL: bash

task:
  name: "Build TWRP"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 6
      memory: 16G

  Build_script:
      - python --version
      - rm -rf /usr/bin/python
      - ln -s /usr/bin/python2 /usr/bin/python
      - python --version
      - mkdir /root/work
      - cd /root/work
      - git clone https://gitlab.com/OrangeFox/sync.git 
      - cd sync
      - bash ./legacy/orangefox_sync_legacy.sh --branch 9.0 --path /root/ofox
      - cd /root/ofox
      - git clone https://gitlab.com/OrangeFox/device/whyred.git device/xiaomi/whyred
      - rm -rf device/xiaomi/whyred/prebuilt/Image.gz-dtb
      - curl -L https://free.keep.sh/LFX3CWvTMuaXS3f6/Image.gz-dtb > device/xiaomi/whyred/prebuilt/Image.gz-dtb
      - export ALLOW_MISSING_DEPENDENCIES=true 
      - export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
      - bash -c "source build/envsetup.sh && lunch omni_whyred-eng && mka recoveryimage"
      - curl --upload-file /root/ofox/out/target/product/whyred/OrangeFox-R11.1-Stable-whyred.img https://free.keep.sh
      - curl --upload-file /root/ofox/out/target/product/whyred/OrangeFox-R11.1-Stable-whyred.zip https://free.keep.sh
