env:
    CIRRUS_SHELL: bash
task:
  name: "Build TWRP"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 6
      memory: 12G
      greedy: true
  Prepare_script:
      - pacman -S pigz aria2 --noconfirm
  Download_script:
      - bash ./download.sh
  Build_script:
      - python --version
      - rm -rf /usr/bin/python
      - ln -s /usr/bin/python2 /usr/bin/python
      - python --version
      - mkdir lineage-19.1
      - cd lineage-19.1
      - repo init -u https://github.com/LineageOS/android.git -b lineage-19.1
      - git clone https://github.com/SeifHossam17/gtaxl-manifests -b lineage-19.1 .repo/local_manifests
      - export CCACHE_DIR=/tmp/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 20G # It took less than 6 GB for less than 2 hours in 2 builds for Samsung A10
      - ccache -o compression=true # Will save times and data to download and upload ccache, also negligible performance issue
      - ccache -z
      - export ALLOW_MISSING_DEPENDENCIES=true 
      - repo sync --force-sync --no-tags --no-clone-bundle -c -j1 --fail-fast
      - . build/envsetup.sh
      - lunch lineage_gtaxlwifi-userdebug
      - mka otapackage
  Upload_script:
      - bash ./upload.sh
