env:
    CIRRUS_SHELL: bash
    RCLONE_CONFIG: "ENCRYPTED[!55f2dbd96fe337fd95485ff73d9638f19545825a2cb11fe45e4f3ee1df56033a0af7861afdf810c1f275674e4d3be9ed!]"
task:
  name: "Build TWRP"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 6
      memory: 16G
  Prepare_script:
      - pacman -S pigz aria2 rclone --noconfirm
  Download_script:
      - bash ./download.sh
  Build_script:
      - python --version
      - rm -rf /usr/bin/python
      - ln -s /usr/bin/python2 /usr/bin/python
      - python --version
      - mkdir /root/work
      - cd /root/work
      - git clone https://gitlab.com/OrangeFox/sync.git 
      - cd sync
      - bash ./legacy/orangefox_sync_legacy.sh --branch 9.0 --path /root/ofox
      - cd /root/ofox
      - git clone https://gitlab.com/OrangeFox/device/whyred.git device/xiaomi/whyred
      - export CCACHE_DIR=/tmp/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 20G # It took less than 6 GB for less than 2 hours in 2 builds for Samsung A10
      - ccache -o compression=true # Will save times and data to download and upload ccache, also negligible performance issue
      - ccache -z
      - export ALLOW_MISSING_DEPENDENCIES=true 
      - export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
      - bash -c "source build/envsetup.sh && lunch omni_whyred-eng && mka recoveryimage"
      - curl --upload-file /root/ofox/out/target/product/whyred/OrangeFox-R11.1-Stable-whyred.img https://free.keep.sh
      - curl --upload-file /root/ofox/out/target/product/whyred/OrangeFox-R11.1-Stable-whyred.zip https://free.keep.sh
  Upload_script:
      - bash ./upload.sh
